# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0054e0c777b4850c58c0b18c28e6e5f6ebf5f8208764379356994e1524a1de04afd1a80c8817eacd1ec0b785065758c737a620624db4c5451ea0c02374f9ca6

test:
  secret_key_base: 45b8358752ca80035fa28579075833013268ece2be1cc3a7dd77f4cd0be02a789a3c57e1af9fdbd3878739da8e21c68a406aaa1f3dd439bb74c7aca7e7fb931e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
